### PR TITLE
Fix state color (css class) of outer dimension

### LINKED ISSUE #102: Wrong state color of outer dimension
## Describe the bug

When implementing sort control, I noticed that the state class of the cube dimension wrapper (outer dimension) only based on the first inner dimension. 
So if the first inner dimension has the state class `UP|OK`, the wrapper also gets the state class `UP|OK` and vice versa, no matter if there are further `DOWN|CRITICAL` dimensions.

## To Reproduce

1. Use the [sort control PR](https://github.com/Icinga/icingaweb2-module-cube/pull/100).
2. Add two or more dimensions.
3. Change sort order and notice the change.

## Expected behavior

The outer dimension should have the correct state class.

## Screenshots

The `prod -> ps` has `berlin (DOWN)` on the first place, so the outer dimension (`prod`) is marked as `down` (red).

Screenshot 2022-12-20 at 15 23 16

The `prod -> ps` has `london (UP)` on the first place, so the outer dimension (`prod`) is marked as `UP` (black).

Screenshot 2022-12-20 at 15 23 01

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #102

### CODE REVIEW

File: library/Cube/CubeRenderer/HostStatusCubeRenderer.php [hunk 1]
```diff
@@ -22,8 +22,12 @@ protected function renderDimensionLabel($name, $row)
     protected function getDimensionClasses($name, $row)
     {
         $classes = parent::getDimensionClasses($name, $row);
-
         $sums = $row;
+
+        if (($next = $this->cube->getDimensionAfter($name)) && isset($this->summaries->{$next->getName()})) {
```
Comment (lippserd) [inline library/Cube/CubeRenderer/HostStatusCubeRenderer.php:27]: Please avoid variable assignments in `if`.

**Review by lippserd — CHANGES_REQUESTED** [review]

**Review by lippserd — APPROVED** [review]
