### PR TITLE
Fix cube do not turn yellow for warning

### LINKED ISSUE #47: Cube do not turn yellow for Warning
Cube is working as expected and is most sought for feature to provide / build necessary dashboard. Only challenge we see is if there is a Warning alert within the cube and no other - it still turns red / as if critical. This sometimes is confusing for command centers to decide the priority on which they should work. If Cube can pick up the Warning and display accordingly it will be great - like in Business Process module

### PR DESCRIPTION
**Pull request by Yonas-net**
Fixes #47

### CODE REVIEW

File: library/Cube/Ido/IdoHostStatusCube.php [hunk 1]
```diff
@@ -17,8 +17,12 @@ public function getAvailableFactColumns()
     {
         return array(
             'hosts_cnt'           => 'COUNT(*)',
-            'hosts_nok'           => 'SUM(CASE WHEN hs.current_state = 0 THEN 0 ELSE 1 END)',
-            'hosts_unhandled_nok' => 'SUM(CASE WHEN hs.current_state != 0'
+            'hosts_nok'           => 'SUM(CASE WHEN hs.current_state = 1 THEN 1 ELSE 0 END)',
+            'hosts_unhandled_nok' => 'SUM(CASE WHEN hs.current_state = 1'
```
Comment (nilmerg) [inline library/Cube/Ido/IdoHostStatusCube.php]: Please get rid of `nok` here as well. Use `hosts_down` and `hosts_down_unhandled` instead.

File: library/Cube/Ido/IdoHostStatusCubeRenderer.php [hunk 2]
```diff
@@ -11,6 +12,19 @@
...
+    {
+        parent::__construct($cube);
+
+        if ($cube instanceof IdoHostStatusCube) {
+            $this->factsPrefix = 'hosts';
+        } else {
+            $this->factsPrefix = 'services';
+        }
+    }
+
```
Comment (nilmerg) [inline library/Cube/Ido/IdoHostStatusCubeRenderer.php]: This is the renderer for hosts and only for hosts. There's no need to differentiate between hosts and services therefore. Please change this so you don't need the `factsPrefix` attribute.

File: library/Cube/Ido/IdoHostStatusCubeRenderer.php [hunk 3]
```diff
@@ -45,16 +63,24 @@ public function renderFacts($facts)
...
-        if ($facts->hosts_nok > 0 && $facts->hosts_nok > $facts->hosts_unhandled_nok) {
-            $parts['critical handled'] = $facts->hosts_nok - $facts->hosts_unhandled_nok;
+        if ($facts->hosts_unreachable > 0 && $facts->hosts_unreachable > $facts->hosts_unhandled_unreachable) {
+            $parts['unreachable handled'] = $facts->hosts_unreachable - $facts->hosts_unhandled_unreachable;
         }
 
-        if ($facts->hosts_cnt > $facts->hosts_nok) {
-            $parts['ok'] = $facts->hosts_cnt - $facts->hosts_nok;
+        if ($facts->hosts_cnt > $facts->hosts_down) {
+            $parts['ok'] = $facts->hosts_cnt - $facts->hosts_down;
```
Comment (nilmerg) [inline library/Cube/Ido/IdoHostStatusCubeRenderer.php]: You forgot to subtract the unreachable hosts.

File: library/Cube/Ido/IdoStatusCubeRenderer.php [hunk 4]
```diff
@@ -8,38 +8,43 @@
 
 class IdoStatusCubeRenderer extends CubeRenderer
 {
-    /** @var string Prefix of the facts */
-    protected $factsPrefix;
 
     public function __construct(Cube $cube)
```
Comment (nilmerg) [inline library/Cube/Ido/IdoStatusCubeRenderer.php]: This constructor override is also redundant, please remove it.

File: library/Cube/Ido/IdoStatusCubeRenderer.php [hunk 5]
```diff
@@ -8,38 +8,43 @@
...
-            $parts['critical handled'] =
-                $facts->{$this->factsPrefix . '_nok'} - $facts->{$this->factsPrefix . '_unhandled_nok'};
+        if ($facts->services_unknown > 0 && $facts->services_unknown > $facts->services_unhandled_unknown) {
+            $parts['unknown handled'] = $facts->services_unknown - $facts->services_unhandled_unknown;
         }
 
-        if ($facts->{$this->factsPrefix . '_cnt'} > $facts->{$this->factsPrefix . '_nok'}) {
-            $parts['ok'] = $facts->{$this->factsPrefix . '_cnt'} - $facts->{$this->factsPrefix . '_nok'};
+        if ($facts->services_cnt > $facts->services_critical) {
+            $parts['ok'] = $facts->services_cnt - $facts->services_critical;
```
Comment (nilmerg) [inline library/Cube/Ido/IdoStatusCubeRenderer.php]: Here you forgot unknown and warning services as well.

File: library/Cube/Ido/IdoStatusCubeRenderer.php [hunk 6]
```diff
@@ -82,13 +87,31 @@ protected function getDimensionClasses($name, $row)
         $classes = parent::getDimensionClasses($name, $row);
 
         $sums = $row;
-        if ($sums->{$this->factsPrefix . '_nok'} > 0) {
+        if ($sums->services_critical > 0) {
             $classes[] = 'critical';
-            if ((int) $sums->{$this->factsPrefix . '_unhandled_nok'} === 0) {
+            if ((int) $sums->services_unhandled_critical === 2) {
```
Comment (nilmerg) [inline library/Cube/Ido/IdoStatusCubeRenderer.php]: Counts, not states :wink:

File: library/Cube/Ido/IdoStatusCubeRenderer.php [hunk 7]
```diff
@@ -82,13 +87,31 @@ protected function getDimensionClasses($name, $row)
...
                 $classes[] = 'handled';
             }
         }
 
+        if ($sums->services_critical < 1) {
```
Comment (nilmerg) [inline library/Cube/Ido/IdoStatusCubeRenderer.php]: Why don't you actually check for warning services?

File: library/Cube/Ido/IdoStatusCubeRenderer.php [hunk 8]
```diff
@@ -82,13 +87,31 @@ protected function getDimensionClasses($name, $row)
...
+            $classes[] = 'warning';
+            if ((int) $sums->services_unhandled_warning === 1) {
```
Comment (nilmerg) [inline library/Cube/Ido/IdoStatusCubeRenderer.php]: Counts, not states :wink:

File: library/Cube/Ido/IdoStatusCubeRenderer.php [hunk 9]
```diff
@@ -82,13 +87,31 @@ protected function getDimensionClasses($name, $row)
...
+                $classes[] = 'handled';
+            }
+        }
+
+        if ($sums->services_critical < 1 && $sums->services_warning < 1) {
```
Comment (nilmerg) [inline library/Cube/Ido/IdoStatusCubeRenderer.php]: Please check for unknown services here.

File: library/Cube/Ido/IdoStatusCubeRenderer.php [hunk 10]
```diff
@@ -82,13 +87,31 @@ protected function getDimensionClasses($name, $row)
...
+            $classes[] = 'unknown';
+            if ((int) $sums->services_unhandled_unknown === 3) {
```
Comment (nilmerg) [inline library/Cube/Ido/IdoStatusCubeRenderer.php]: Counts, still :stuck_out_tongue_winking_eye:
