### PR TITLE
Drop IcingaDB `hosts_(unhandled)_unreachable` columns

### LINKED ISSUE #145: Failed to load dimensions
## Describe the bug

Adding a dimension and right after the form redirects results to following stack trace.

Bildschirmfoto 2023-08-14 um 15 21 08

Caused by https://github.com/Icinga/icingadb-web/pull/803/commits/87db46023cef7daa26f298d5074b0b20775dfaf0

```bash
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'f.hosts_unreachable_unhandled' in 'field list'
```

Caused by https://github.com/Icinga/icingadb-web/pull/803/commits/b2bbe2c0d04cb8c8b1331cb731239bc008255563

### PR DESCRIPTION
**Pull request by yhabteab**
fixes #145

### CODE REVIEW

File: library/Cube/CubeRenderer/HostStatusCubeRenderer.php [hunk 1]
```diff
@@ -59,20 +59,34 @@ public function renderFacts($facts)
...
         }
 
         if ($facts->hosts_down > 0 && $facts->hosts_down > $facts->hosts_unhandled_down) {
             $parts['critical handled'] = $facts->hosts_down - $facts->hosts_unhandled_down;
         }
 
-        if ($facts->hosts_unreachable > 0 && $facts->hosts_unreachable > $facts->hosts_unhandled_unreachable) {
+        if (
+            isset($facts->hosts_unreachable)
+            && isset($facts->hosts_unhandled_unreachable)
```
Comment (sukhwinder33445) [inline library/Cube/CubeRenderer/HostStatusCubeRenderer.php:72]: Please use `isset($param1, $param2)`.

**Review by sukhwinder33445 — APPROVED** [review]
